from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import secrets
import os
import textwrap

# Read the host directory from the environment map, defaulting to current dir for testing
HOST_DIR = os.getenv("HOST_DIR", ".")
ENV_FILE_PATH = os.path.join(HOST_DIR, ".env.global")

app = FastAPI(title="OpenFMR Setup API")

# Setup CORS to allow requests from the React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class SetupRequest(BaseModel):
    facility_name: str
    facility_id: str
    host_ip: str
    admin_username: str
    admin_password: str
    timezone: str = "UTC"

@app.post("/api/setup")
async def process_setup(data: SetupRequest):
    """
    Receives user input from the setup wizard, generates secure passwords,
    and writes the master .env.global file directly to the host machine.
    """
    try:
        # Generate secure random strings for passwords and secrets
        postgres_root_password = secrets.token_urlsafe(32)
        cr_db_password = secrets.token_urlsafe(32)
        hfr_db_password = secrets.token_urlsafe(32)
        shr_db_password = secrets.token_urlsafe(32)
        keycloak_db_password = secrets.token_urlsafe(32)
        jwt_secret_key = secrets.token_urlsafe(32)
        openhim_root_password = secrets.token_urlsafe(32)
        lmis_db_password = secrets.token_urlsafe(32)
        hwr_db_password = secrets.token_urlsafe(32)
        ts_db_password = secrets.token_urlsafe(32)

        # Build the .env.global file content using textwrap for clean formatting
        # We integrate the user inputs (facility info, admin creds, host ip)
        env_content = textwrap.dedent(f"""\
            ###############################################################################
            # OpenFMR Master Deployment Environment Variables
            # GENERATED BY SETUP WIZARD
            ###############################################################################
            
            # ── General Configuration ────────────────────────────────────────────────────────
            FACILITY_NAME="{data.facility_name}"
            FACILITY_ID="{data.facility_id}"
            TIMEZONE={data.timezone}
            HOST_IP={data.host_ip}
            OPENFMR_NETWORK=openfmr_global_net
            
            # ── Network & Routing ────────────────────────────────────────────────────────────
            # The base domain/IP where the system is hosted
            BASE_URL=http://{data.host_ip}
            
            # ── Global Master Passwords ──────────────────────────────────────────────────────
            POSTGRES_ROOT_PASSWORD={postgres_root_password}
            JWT_SECRET_KEY={jwt_secret_key}
            
            # ── OpenHIM Configuration ────────────────────────────────────────────────────────
            OPENHIM_ROOT_PASSWORD={openhim_root_password}
            OPENHIM_API_PORT=8085
            OPENHIM_CONSOLE_PORT=9000
            
            # ── Keycloak Configuration ───────────────────────────────────────────────────────
            KEYCLOAK_DB_PASSWORD={keycloak_db_password}
            KEYCLOAK_ADMIN_USER={data.admin_username}
            KEYCLOAK_ADMIN_PASSWORD={data.admin_password}
            KEYCLOAK_PORT=8443
            
            # ── Database Passwords (Individual Service Modules) ──────────────────────────────
            CR_DB_PASSWORD={cr_db_password}
            HFR_DB_PASSWORD={hfr_db_password}
            HWR_DB_PASSWORD={hwr_db_password}
            TS_DB_PASSWORD={ts_db_password}
            SHR_DB_PASSWORD={shr_db_password}
            LMIS_DB_PASSWORD={lmis_db_password}
            
            # ── Service Specific Database URLs ───────────────────────────────────────────────
            CR_STAGING_DB_URL=postgresql://postgres:{cr_db_password}@openfmr-cr-staging-postgres:5432/client_registry
            HFR_STAGING_DB_URL=postgresql://postgres:{hfr_db_password}@openfmr-hfr-staging-postgres:5432/facility_registry
            HWR_STAGING_DB_URL=postgresql://postgres:{hwr_db_password}@openfmr-hwr-staging-postgres:5432/worker_registry
            LMIS_STAGING_DB_URL=postgresql://postgres:{lmis_db_password}@openfmr-lmis-staging-postgres:5432/logistics_registry
            
            # ── FHIR Endpoints ───────────────────────────────────────────────────────────────
            CR_FHIR_BASE_URL=http://openfmr-cr-fhir-server:8080/fhir
            HFR_FHIR_BASE_URL=http://openfmr-hfr-fhir-server:8081/fhir
            HWR_FHIR_BASE_URL=http://openfmr-hwr-fhir-server:8082/fhir
            TS_FHIR_BASE_URL=http://openfmr-ts-fhir-server:8083/fhir
            SHR_FHIR_BASE_URL=http://openfmr-shr-fhir-server:8084/fhir
            LMIS_FHIR_BASE_URL=http://openfmr-lmis-fhir-server:8086/fhir
            """)

        # Write to the host mount
        with open(ENV_FILE_PATH, "w") as f:
            f.write(env_content)

        return {"message": "Configuration successfully generated and written to .env.global"}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to write configuration: {str(e)}")
